### PR TITLE
Implemented request scoped translations

### PR DESCRIPTION
**Pull request by AnderUstarroz**
There is a serious issue on current implementation, the same Babel instance is shared globally, which means that the request of one user can change the language of another user request depending on race conditions. This PR takes care of scoping a single Babel instance per request.

### CODE REVIEW

**Review by caner-cetin — APPROVED** [review]
This PR would make fastapi-babel production ready by itself. thinking latest release is more than 1 years ago, I think someone should fork with this PR.

**Comment by Legopapurida** [comment]
I have reviewed your changes. You have implemented good changes but there are a few considerations for request.state.
I will change the codes in the next version in another way.
we must implement a request local proxy to handle the gettext as a global variable throughout the files and packages (without passing the request object to do that.

**Comment by Legopapurida** [comment]
I have tested the code in pull request and it does work fine. 
 
Thanks for resolving this problem.

**Comment by AnderUstarroz** [comment]
> I have reviewed your changes. You have implemented good changes but there are a few considerations for request.state. I will change the codes in the next version in another way. we must implement a request local proxy to handle the gettext as a global variable throughout the files and packages (without passing the request object to do that.

Sorry for not answering earlier... I saw that you remove the Singleton from core.py, [then Babel.instance won't be needed anymore](https://github.com/Anbarryprojects/fastapi-babel/blob/882d1465e952e0b9fe3dbae4df475cff67029514/fastapi_babel/core.py#L18) right? Thanks for taking the time to review the PR and making a new release 👍

**Comment by AnderUstarroz** [comment]
Actually...  are you sure we can just get rid of the [Babel.instance](https://github.com/Anbarryprojects/fastapi-babel/blob/882d1465e952e0b9fe3dbae4df475cff67029514/fastapi_babel/core.py#L18)?  It seems to be used also in the [make_gettext](https://github.com/Anbarryprojects/fastapi-babel/blob/882d1465e952e0b9fe3dbae4df475cff67029514/fastapi_babel/core.py#L108) function.

**Pull request merged**
